//! Walks a folder yielding (path, contents) for files that look like text
//! and aren't ignored by .gitignore / hidden rules.
//!
//! Filters applied:
//! - `ignore` crate walker excludes hidden files, .gitignore-listed paths,
//!   and the user's global ignore rules.
//! - Binary detection: read the first 4 KB and decode as UTF-8; if that
//!   fails, skip the file.
//! - Size cap: files larger than `MAX_FILE_BYTES` are skipped (likely
//!   autogenerated or not source).

use anyhow::{Context, Result};
use ignore::WalkBuilder;
use std::path::{Path, PathBuf};

pub const MAX_FILE_BYTES: u64 = 256 * 1024; // 256 KB

pub struct ScannedFile {
    pub path: PathBuf,
    pub contents: String,
}

/// Walk `root` and return an iterator over scanned text files.
/// Errors during traversal are propagated as iterator items; the caller
/// can choose to log-and-skip vs. abort.
pub fn walk(root: &Path) -> Result<impl Iterator<Item = Result<ScannedFile>>> {
    if !root.exists() {
        anyhow::bail!("not found: {}", root.display());
    }
    if !root.is_dir() {
        anyhow::bail!("not a directory: {}", root.display());
    }
    let walker = WalkBuilder::new(root)
        .hidden(true)        // skip hidden files (default true, explicit for clarity)
        .require_git(false)  // honour .gitignore even outside a git repo
        .git_ignore(true)    // honour .gitignore
        .git_global(true)    // honour user's global ignore
        .git_exclude(true)   // honour .git/info/exclude
        .build();

    Ok(walker.filter_map(|entry| {
        let entry = match entry {
            Ok(e) => e,
            Err(e) => return Some(Err(anyhow::anyhow!("walk error: {e}"))),
        };
        // Skip directories themselves; we only yield files.
        if !entry.file_type().map(|t| t.is_file()).unwrap_or(false) {
            return None;
        }
        let path = entry.path().to_path_buf();
        Some(read_text_file(path))
    }))
}

fn read_text_file(path: PathBuf) -> Result<ScannedFile> {
    let bytes = std::fs::read(&path)
        .with_context(|| format!("read {}", path.display()))?;
    if bytes.len() as u64 > MAX_FILE_BYTES {
        anyhow::bail!(
            "skipped (over {} bytes): {}",
            MAX_FILE_BYTES,
            path.display()
        );
    }
    if !looks_like_text(&bytes) {
        anyhow::bail!("skipped (binary): {}", path.display());
    }
    let contents = String::from_utf8(bytes)
        .with_context(|| format!("decode utf-8 from {}", path.display()))?;
    Ok(ScannedFile { path, contents })
}

/// Heuristic: a file is "text" if the first 4 KB is valid UTF-8 and
/// contains no null bytes. This matches what most diff/grep tools do.
fn looks_like_text(bytes: &[u8]) -> bool {
    let probe = &bytes[..bytes.len().min(4096)];
    if probe.contains(&0) {
        return false;
    }
    std::str::from_utf8(probe).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write(dir: &Path, name: &str, contents: &[u8]) -> PathBuf {
        let p = dir.join(name);
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::write(&p, contents).unwrap();
        p
    }

    #[test]
    fn looks_like_text_accepts_utf8() {
        assert!(looks_like_text(b"hello world\n"));
        assert!(looks_like_text("café".as_bytes()));
    }

    #[test]
    fn looks_like_text_rejects_null_bytes() {
        assert!(!looks_like_text(b"hello\x00world"));
    }

    #[test]
    fn walk_yields_plain_files() {
        let tmp = TempDir::new().unwrap();
        write(tmp.path(), "a.txt", b"hello\n");
        write(tmp.path(), "b.rs", b"fn main() {}\n");
        let mut names: Vec<String> = walk(tmp.path())
            .unwrap()
            .filter_map(|r| r.ok())
            .map(|f| f.path.file_name().unwrap().to_string_lossy().to_string())
            .collect();
        names.sort();
        assert_eq!(names, vec!["a.txt", "b.rs"]);
    }

    #[test]
    fn walk_respects_gitignore() {
        let tmp = TempDir::new().unwrap();
        // The `ignore` crate honours .gitignore only inside a git repo OR
        // when the root has a .gitignore directly. Both work here.
        write(tmp.path(), ".gitignore", b"ignored.txt\n");
        write(tmp.path(), "kept.txt", b"keep me\n");
        write(tmp.path(), "ignored.txt", b"skip me\n");
        let names: Vec<String> = walk(tmp.path())
            .unwrap()
            .filter_map(|r| r.ok())
            .map(|f| f.path.file_name().unwrap().to_string_lossy().to_string())
            .filter(|n| n != ".gitignore")
            .collect();
        assert_eq!(names, vec!["kept.txt"]);
    }

    #[test]
    fn walk_skips_hidden() {
        let tmp = TempDir::new().unwrap();
        write(tmp.path(), ".hidden", b"x");
        write(tmp.path(), "visible.txt", b"y");
        let names: Vec<String> = walk(tmp.path())
            .unwrap()
            .filter_map(|r| r.ok())
            .map(|f| f.path.file_name().unwrap().to_string_lossy().to_string())
            .collect();
        assert_eq!(names, vec!["visible.txt"]);
    }

    #[test]
    fn walk_skips_binary() {
        let tmp = TempDir::new().unwrap();
        write(tmp.path(), "image.png", b"\x89PNG\x00binary stuff");
        write(tmp.path(), "code.rs", b"fn main() {}");
        let results: Vec<_> = walk(tmp.path()).unwrap().collect();
        // The binary file appears as Err(...) so the caller can log it.
        let oks: Vec<_> = results.iter().filter_map(|r| r.as_ref().ok()).collect();
        let errs: Vec<_> = results.iter().filter_map(|r| r.as_ref().err()).collect();
        assert_eq!(oks.len(), 1);
        assert_eq!(oks[0].path.file_name().unwrap(), "code.rs");
        assert!(errs.iter().any(|e| format!("{e:#}").contains("binary")));
    }

    #[test]
    fn walk_errors_for_missing_root() {
        let tmp = TempDir::new().unwrap();
        let bogus = tmp.path().join("does-not-exist");
        assert!(walk(&bogus).is_err());
    }

    #[test]
    fn walk_errors_for_file_root() {
        let tmp = TempDir::new().unwrap();
        let file = write(tmp.path(), "plain.txt", b"hi");
        assert!(walk(&file).is_err());
    }
}
